version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "gomod"
    directory: "container-files/opt/build/entrypoint"
    schedule:
      interval: "weekly"
