name: auto-merge

on:
    pull_request:

jobs:
    auto-merge:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Automerge
              uses: ahmadnassri/action-dependabot-auto-merge@v2
              with:
                  target: minor
                  github-token: ${{ secrets.GH_RW_TOKEN }}
                  approve: true
